version: "3"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    # command: /opt/bitnami/kafka/bin/kafka-topics.sh --if-not-exists --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic OfferTopic

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "my_db"
    ports:
      - "3306:3306"

  customer:
    # platform: linux/amd64
    build: ./customer
    volumes:
      - ./customer:/home/app/

    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: my_db
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kafka

  marketer:
    # platform: linux/amd64
    build: ./marketer
    volumes:
      - ./marketer:/home/app/
    ports:
      - "3001:3001"
    depends_on:
      - db
      - kafka
